version: "3"

services:

  boz-nginx:
    image: nginx:latest
    container_name: bookofzeus
    labels:
      name: "bookofzeus.dev"
    hostname: "bookofzeus.dev"
    ports:
     - "8081:80"
    volumes:
      - /home/eric/Git/bookofzeus.github.io/:/usr/share/nginx/html
      - ./bookofzeus_nginx_configs:/etc/nginx/conf.d
